# Generated by Django 4.2.11 on 2024-04-18 20:32

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRide',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Valor')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Distância')),
                ('start', models.CharField(max_length=300, verbose_name='Começo')),
                ('end', models.CharField(max_length=300, verbose_name='Chegada')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('timeStart', models.DateTimeField(blank=True, editable=False, verbose_name='Início')),
                ('timeEnd', models.DateTimeField(verbose_name='Fim')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'historical Corridas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Valor')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Distância')),
                ('start', models.CharField(max_length=300, verbose_name='Começo')),
                ('end', models.CharField(max_length=300, verbose_name='Chegada')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('timeStart', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('timeEnd', models.DateTimeField(verbose_name='Fim')),
            ],
            options={
                'verbose_name': 'Corrida',
                'verbose_name_plural': 'Corridas',
                'ordering': ['timeStart'],
            },
        ),
    ]
