# Generated by Django 4.2.11 on 2024-04-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_number_user_phone_remove_pilot_motorcycle'),
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distância'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='end',
            field=models.CharField(max_length=100, verbose_name='Chegada Local'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='pilot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.pilot', verbose_name='Piloto'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='start',
            field=models.CharField(max_length=100, verbose_name='Começo Local'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='status',
            field=models.CharField(choices=[('0', 'Criada'), ('1', 'Iniciada'), ('2', 'Finalizada'), ('3', 'Cancelada')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='timeEnd',
            field=models.DateTimeField(verbose_name='Fim Tempo'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='timeStart',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Início Tempo'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distância'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end',
            field=models.CharField(max_length=100, verbose_name='Chegada Local'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pilot_rides', to='users.pilot', verbose_name='Piloto'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start',
            field=models.CharField(max_length=100, verbose_name='Começo Local'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('0', 'Criada'), ('1', 'Iniciada'), ('2', 'Finalizada'), ('3', 'Cancelada')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='timeEnd',
            field=models.DateTimeField(verbose_name='Fim Tempo'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='timeStart',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Início Tempo'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
    ]
