# Generated by Django 4.2.11 on 2024-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_historicalride_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalride',
            name='stopPlace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Parada'),
        ),
        migrations.AddField(
            model_name='ride',
            name='stopPlace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Parada'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chegada Local'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='timeEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim Tempo'),
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chegada Local'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='timeEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim Tempo'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Valor'),
        ),
    ]
