# Generated by Django 4.2.11 on 2024-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_historicalride_stopplace_ride_stopplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distância'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distância'),
        ),
    ]
