# Generated by Django 4.2.11 on 2024-05-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_historicalride_distance_alter_ride_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='status',
            field=models.CharField(choices=[('created', 'Criada'), ('started', 'Iniciada'), ('finished', 'Finalizada'), ('canceled', 'Cancelada')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('created', 'Criada'), ('started', 'Iniciada'), ('finished', 'Finalizada'), ('canceled', 'Cancelada')], default=0, verbose_name='Status'),
        ),
    ]
