# Generated by Django 4.2.11 on 2024-05-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_alter_historicalride_status_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalride',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Distância'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='end',
            field=models.CharField(default=0, max_length=100, verbose_name='Chegada Local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalride',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Distância'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='end',
            field=models.CharField(default=0, max_length=100, verbose_name='Chegada Local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
