# Generated by Django 4.2.11 on 2024-04-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_number_user_phone_remove_pilot_motorcycle'),
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='owner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to='users.pilot', verbose_name='Proprietário'),
            preserve_default=False,
        ),
    ]
