# Generated by Django 4.2.11 on 2024-04-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='motorcycle',
        ),
    ]
